DEFAULT_EVAPORATOR_TEMP_C = 10
DEFAULT_CONDENSER_APPROACH_C = 10
DEFAULT_SUPERHEAT_C = 5
DEFAULT_SUBCOOLING_C = 5
DEFAULT_COMPRESSOR_EFFICIENCY = 0.70
DEFAULT_DAYS_PER_MONTH = 30
PLACEHOLDER_TARIFF_QAR_PER_KWH = 0.18
